# render.yaml
services:
  - type: web
    name: agents-exotics
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class eventlet -w 1 --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: AUTOTRADER_USERNAME
        sync: false
      - key: AUTOTRADER_PASSWORD
        sync: false
      - key: API_URL
        sync: false
    env:
      PYTHON_VERSION: "3.11.9"  # or your version